###
GET http://localhost:8080/reservation-new-async?storeId=VQtTGTCc13EWulU5sZmI
Content-Type: application/json

###
GET http://localhost:8080/stores?storeId=11fj3imWYEP7KP4Kfjco
Content-Type: application/json

###
GET http://localhost:8080/board?boardId=0YhQlOD7AdwgATAsYrJW
Content-Type: application/json

###
GET http://localhost:8080/item-store?storeId=0schMVN8hmowr9foiFjo
Content-Type: application/json

###
PUT http://localhost:8080/reservation-fail?reservationId=452wW3Gk0WucxiB7Adlv
Content-Type: application/json

###
DELETE http://localhost:8080/item?itemId=gggdIiT52VdqidGUbcJ1
Content-Type: application/json

###
PUT http://localhost:8080/store/open?storeId=VQtTGTCc13EWulU5sZmI
Content-Type: application/json