name: Java CD with Gradle

on:
  push:
    branches: [ "develop", "main" ]

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Deploy JAR on Remote Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
               mkdir -p ~/.ssh
               echo "${SSH_PRIVATE_KEY}" > ~/.ssh/github_rsa
               chmod 400 ~/.ssh/github_rsa
               ssh-keyscan ${REMOTE_HOST} >> ~/.ssh/known_hosts
               ssh -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} << 'EOF'
               ps aux | grep mayoweb-0.0.1-SNAPSHOT.jar | grep -v grep | awk '{print $2}' | xargs kill -9
               cd app
               nohup java -jar mayoweb-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
               EOF