name: Java CI with Gradle

on:
  pull_request:
    branches: [ "develop", "main" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Write Firebase JSON file
        env:
          FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
        run: echo "${{ secrets.FIREBASE_JSON }}" > build/resources/main/key/mayo-app-280d4.json

      - name: Upload JAR and JSON to Remote Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/github_rsa
          chmod 400 ~/.ssh/github_rsa
          ssh-keyscan ${REMOTE_HOST} >> ~/.ssh/known_hosts
          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no build/libs/*.jar ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}
          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no build/resources/main/key/mayo-app-280d4.json ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}